DELETE FROM university.specialty;
ALTER SEQUENCE university.specialty_specialty_id_seq RESTART WITH 1;

INSERT INTO university.specialty(name) VALUES ('01.03.02 - Прикладная математика и информатика');
INSERT INTO university.specialty(name) VALUES ('01.04.02 - Прикладная математика и информатика');
INSERT INTO university.specialty(name) VALUES ('02.04.03 - Математическое обеспечение и администрирование информационных систем');
INSERT INTO university.specialty(name) VALUES ('07.04.04 - Градостроительство');
INSERT INTO university.specialty(name) VALUES ('09.03.01 - Информатика и вычислительная техника');
INSERT INTO university.specialty(name) VALUES ('09.03.02 - Информационные системы и технологии');
INSERT INTO university.specialty(name) VALUES ('09.03.03 - Прикладная информатика');
INSERT INTO university.specialty(name) VALUES ('09.03.04 - Программная инженерия');
INSERT INTO university.specialty(name) VALUES ('09.04.01 - Информатика и вычислительная техника');
INSERT INTO university.specialty(name) VALUES ('09.04.02 - Информационные системы и технологии');
INSERT INTO university.specialty(name) VALUES ('09.04.03 - Прикладная информатика');
INSERT INTO university.specialty(name) VALUES ('09.04.04 - Программная инженерия');
INSERT INTO university.specialty(name) VALUES ('10.03.01 - Информационная безопасность');
INSERT INTO university.specialty(name) VALUES ('10.04.01 - Информационная безопасность');
INSERT INTO university.specialty(name) VALUES ('11.03.02 - Инфокоммуникационные технологии и системы связи');
INSERT INTO university.specialty(name) VALUES ('11.03.03 - Конструирование и технология электронных средств');
INSERT INTO university.specialty(name) VALUES ('11.04.02 - Инфокоммуникационные технологии и системы связи');
INSERT INTO university.specialty(name) VALUES ('11.04.03 - Конструирование и технология электронных средств');
INSERT INTO university.specialty(name) VALUES ('12.03.01 - Приборостроение');
INSERT INTO university.specialty(name) VALUES ('12.03.02 - Оптотехника');
INSERT INTO university.specialty(name) VALUES ('12.03.03 - Фотоника и оптоинформатика');
INSERT INTO university.specialty(name) VALUES ('12.03.04 - Биотехнические системы и технологии');
INSERT INTO university.specialty(name) VALUES ('12.03.05 - Лазерная техника и лазерные технологии');
INSERT INTO university.specialty(name) VALUES ('12.04.01 - Приборостроение');
INSERT INTO university.specialty(name) VALUES ('12.04.02 - Оптотехника');
INSERT INTO university.specialty(name) VALUES ('12.04.03 - Фотоника и оптоинформатика');
INSERT INTO university.specialty(name) VALUES ('12.04.04 - Биотехнические системы и технологии');
INSERT INTO university.specialty(name) VALUES ('12.04.05 - Лазерная техника и лазерные технологии');
INSERT INTO university.specialty(name) VALUES ('12.05.01 - Электронные и оптико-электронные приборы и системы специального назначения');
INSERT INTO university.specialty(name) VALUES ('13.03.01 - Теплоэнергетика и теплотехника');
INSERT INTO university.specialty(name) VALUES ('13.03.02 - Электроэнергетика и электротехника');
INSERT INTO university.specialty(name) VALUES ('13.04.02 - Электроэнергетика и электротехника');
INSERT INTO university.specialty(name) VALUES ('14.03.01 - Ядерная энергетика и теплофизика');
INSERT INTO university.specialty(name) VALUES ('15.03.02 - Технологические машины и оборудование');
INSERT INTO university.specialty(name) VALUES ('15.03.04 - Автоматизация технологических процессов и производств');
INSERT INTO university.specialty(name) VALUES ('15.03.06 - Мехатроника и робототехника');
INSERT INTO university.specialty(name) VALUES ('15.04.02 - Технологические машины и оборудование');
INSERT INTO university.specialty(name) VALUES ('15.04.04 - Автоматизация технологических процессов и производств');
INSERT INTO university.specialty(name) VALUES ('15.04.06 - Мехатроника и робототехника');
INSERT INTO university.specialty(name) VALUES ('16.03.01 - Техническая физика');
INSERT INTO university.specialty(name) VALUES ('16.03.03 - Холодильная, криогенная техника и системы жизнеобеспечения');
INSERT INTO university.specialty(name) VALUES ('16.04.01 - Техническая физика');
INSERT INTO university.specialty(name) VALUES ('16.04.03 - Холодильная, криогенная техника и системы жизнеобеспечения');
INSERT INTO university.specialty(name) VALUES ('18.03.01 - Химическая технология');
INSERT INTO university.specialty(name) VALUES ('18.03.02 - Энерго- и ресурсосберегающие процессы в химической технологии, нефтехимии и биотехнологии');
INSERT INTO university.specialty(name) VALUES ('18.04.01 - Химическая технология');
INSERT INTO university.specialty(name) VALUES ('18.04.02 - Энерго- и ресурсосберегающие процессы в химической технологии, нефтехимии и биотехнологии');
INSERT INTO university.specialty(name) VALUES ('19.03.01 - Биотехнология');
INSERT INTO university.specialty(name) VALUES ('19.03.02 - Продукты питания из растительного сырья');
INSERT INTO university.specialty(name) VALUES ('19.03.03 - Продукты питания животного происхождения');
INSERT INTO university.specialty(name) VALUES ('19.04.01 - Биотехнология');
INSERT INTO university.specialty(name) VALUES ('19.04.02 - Продукты питания из растительного сырья');
INSERT INTO university.specialty(name) VALUES ('19.04.03 - Продукты питания животного происхождения');
INSERT INTO university.specialty(name) VALUES ('20.04.01 - Техносферная безопасность');
INSERT INTO university.specialty(name) VALUES ('23.03.03 - Эксплуатация транспортно-технологических машин и комплексов');
INSERT INTO university.specialty(name) VALUES ('23.04.03 - Эксплуатация транспортно-технологических машин и комплексов');
INSERT INTO university.specialty(name) VALUES ('24.03.02 - Системы управления движением и навигация');
INSERT INTO university.specialty(name) VALUES ('24.04.01 - Ракетные комплексы и космонавтика');
INSERT INTO university.specialty(name) VALUES ('24.04.02 - Системы управления движением и навигация');
INSERT INTO university.specialty(name) VALUES ('27.03.04 - Управление в технических системах');
INSERT INTO university.specialty(name) VALUES ('27.03.05 - Инноватика');
INSERT INTO university.specialty(name) VALUES ('27.04.01 - Стандартизация и метрология');
INSERT INTO university.specialty(name) VALUES ('27.04.02 - Управление качеством');
INSERT INTO university.specialty(name) VALUES ('27.04.03 - Системный анализ и управление');
INSERT INTO university.specialty(name) VALUES ('27.04.04 - Управление в технических системах');
INSERT INTO university.specialty(name) VALUES ('27.04.05 - Инноватика');
INSERT INTO university.specialty(name) VALUES ('27.04.07 - Наукоемкие технологии и экономика инноваций');
INSERT INTO university.specialty(name) VALUES ('27.04.08 - Управление интеллектуальной собственностью');
INSERT INTO university.specialty(name) VALUES ('38.03.01 - Экономика');
INSERT INTO university.specialty(name) VALUES ('38.03.02 - Менеджмент');
INSERT INTO university.specialty(name) VALUES ('38.03.05 - Бизнес-информатика');
INSERT INTO university.specialty(name) VALUES ('38.04.01 - Экономика');
INSERT INTO university.specialty(name) VALUES ('38.04.05 - Бизнес-информатика');
INSERT INTO university.specialty(name) VALUES ('38.05.02 - Таможенное дело');
INSERT INTO university.specialty(name) VALUES ('44.03.04 - Профессиональное обучение');
INSERT INTO university.specialty(name) VALUES ('45.03.04 - Интеллектуальные системы в гуманитарной сфере');
INSERT INTO university.specialty(name) VALUES ('45.04.04 - Интеллектуальные системы в гуманитарной среде');

SELECT * FROM university.specialty;