create table awm.direction (
    direction_id number generated by default as identity primary key,
    name varchar2(2000) not null
) tablespace awm;

create table awm.speciality (
    speciality_id number generated by default as identity primary key,
    direction_id number not null references awm.direction,
    name varchar2(2000) not null,
    code char(8) not null
) tablespace awm;

create table awm.university (
    university_id number generated by default as identity primary key,
    name varchar2(2000) not null
) tablespace awm;

create table awm.mega_faculty (
    mega_faculty_id number generated by default as identity primary key,
    university_id number not null references awm.university,
    name varchar2(2000) not null
) tablespace awm;

create table awm.faculty (
    faculty_id number generated by default as identity primary key,
    mega_faculty_id number not null references awm.mega_faculty,
    name varchar2(2000) not null
) tablespace awm;

create table awm.study_group (
    study_group_id number generated by default as identity primary key,
    faculty_id number not null references awm.faculty,
    speciality_id number not null references awm.speciality,
    code char(10)
) tablespace awm;